title: taki-on
description: > # this means to ignore newlines until "show_exerpts:"
  ğŸ‘‹ Hello! ì•ˆë…•í•˜ì„¸ìš”! ã“ã‚“ã«ã¡ã¯ã€‚
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://taki-on.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: taki__on
github_username:  taki-on

paginate: 5
paginate_path: "/blog/page:num/"

remote_theme: bitbrain/jekyll-dash
plugins:
  - jekyll-feed

# Theme set up
dash:
  avatar_source: github
  github_username: taki-on
  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/taki__on
      icon: twitter-square
      color: teal
    - url: https://github.com/taki-on
      icon: github-square
      color: teal

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
