title: taki-on
description: > # this means to ignore newlines until "show_exerpts:"
  ğŸ‘‹ Hello! ì•ˆë…•í•˜ì„¸ìš”! ã“ã‚“ã«ã¡ã¯ã€‚
show_excerpts: false # set to true to show excerpts on the homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://taki-on.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: taki__on
github_username:  taki-on

remote_theme: tareqdandachi/jekyll-shell-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji

header_pages:
  - index.md
  - about.md

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
